language: generic 
sudo: required
services: 
    - docker

before-install:
    - docker build -t nchamberlain05/react-test -f ./client/dockerfile.dev ./client
  
script:
 - docker run -e CI=TRUE nchamberlain05/react-test npm test

after_success:
 - docker build -t nchamberlain05/multi-client ./client
 - docker build -t nchamberlain05/multi-nginx ./nginx
 - docker build -t nchamberlain05/multi-server ./server
 - docker build -t nchamberlain05/multi-worker ./worker
 #Login To Docker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #Build to Prod
 - docker push nchamberlain05/multi-client
 - docker push nchamberlain05/multi-nginx
 - docker push nchamberlain05/multi-server
 - docker push nchamberlain05/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: multidocker-env
    bucket_name: elasticbeanstalk-us-east-2-107261137171
    bucker-path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    