language: generic 
sudo: required
services: 
    - docker

before-install:
    - docker build -t navarro-chamberlain/react-test -f ./client/dockerfile.dev ./client
  
script:
 - docker run -e CI=TRUE navarro-chamberlain/react-test npm test

after_success:
 - docker build -t navarro-chamberlain/multi-client ./client
 - docker build -t navarro-chamberlain/multi-nginx ./nginx
 - docker build -t navarro-chamberlain/multi-server ./server
 - docker build -t navarro-chamberlain/multi-worker ./worker
 - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
 - docker push navarro-chamberlain/multi-client
 - docker push navarro-chamberlain/multi-nginx
 - docker push navarro-chamberlain/multi-server
 - docker push navarro-chamberlain/multi-worker